### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by exhaustivee** [zisra/create-discord-guild#5]
literally just doesnt work. It just creates a regular server not a guild

**Comment by zisra** [comment]
@exhaustivee Last time I checked, a guild and regular server are the same thing. Am I missing something here?

**Comment by exhaustivee** [comment]
I assumed this used a bot to make a guild which is a new discord feature kind of like clans where it gives you a tag next to your name. I suggest changing the name because It can be misleading. [Info on guilds](https://support.discord.com/hc/en-us/articles/23187611406999-Guilds-FAQ).

**Comment by zisra** [comment]
@exhaustivee 
Ah, I understand the issue now. This project was made before "guilds" existed as a name in the user interface. Previously, "guilds" meant the same thing as server, it was just the equivalent term of server as used in the API. 

So this project only makes servers.
